import pandas as pd
import numpy as np
import re


def limpieza_texto(text,id_tesis):
    
    tesis_borrar = ''.join(id_tesis)
    text_aux = text.strip()
    text_aux = text_aux.replace('\n\n','###')
    text_aux = text_aux.replace('\n',' ')
    text_aux = text_aux.replace('Ley de Amparo','ley_de_amparo')
    text_aux = text_aux.replace('Competencia Económica','competencia_económica')
    text_aux = text_aux.replace('Fomento a la Competencia','Fomento a la competencia')
    text_aux = text_aux.replace(r'1o.','01')
    text_aux = text_aux.replace(r'1°','01')
    text_aux = text_aux.replace(r'1º','01')
    text_aux = text_aux.replace('del año','de')
    text_aux = text_aux.replace('Presidente Ponente','Presidente-ponente')
    text_aux = text_aux.replace('autorizados por el Secretario','autorizados por el secr.')
    text_aux = text_aux.replace('Ponente: La publicación no menciona el nombre del ponente.','La publicación no menciona el nombre del ponente.')
    text_aux = text_aux.replace(' en sesión de 5 de marzo de 1996','')
    text_aux = text_aux.replace('29 se septiembre de 1993','29 de septiembre de 1993')
    text_aux = text_aux.replace('12 se agosto de 1976','12 de agosto de 1976')
    text_aux = text_aux.replace('10 de 1988','10 de FALTAMES de 1988')
    text_aux = text_aux.replace('* de abril de 1969','99 de abril de 1969')
    text_aux = text_aux.replace('7 de agosto de 1984. 7 de agosto de 1984.','7 de agosto de 1984.')
    text_aux = text_aux.replace('4 de julio de 975','4 de julio de 1975')
    text_aux = text_aux.replace('Pág. 1 de 1 ','')
    text_aux = text_aux.replace('Pág. 1 de 2 ','')
    text_aux = text_aux.replace('Pág. 2 de 2 ','')
    text_aux = text_aux.replace('Pág. 1 de 3 ','')
    text_aux = text_aux.replace('Pág. 2 de 3 ','')
    text_aux = text_aux.replace('Pág. 3 de 3 ','')
    text_aux = text_aux.replace('Pág. 1 de 4 ','')
    text_aux = text_aux.replace('Pág. 2 de 4 ','')
    text_aux = text_aux.replace('Pág. 3 de 4 ','')
    text_aux = text_aux.replace('Pág. 4 de 4 ','')
    text_aux = text_aux.replace('Pág. 1 de 5 ','')
    text_aux = text_aux.replace('Pág. 2 de 5 ','')
    text_aux = text_aux.replace('Pág. 3 de 5 ','')
    text_aux = text_aux.replace('Pág. 4 de 5 ','')
    text_aux = text_aux.replace('Pág. 5 de 5 ','')
    text_aux = text_aux.replace('Pág. 1 de 6 ','')
    text_aux = text_aux.replace('Pág. 2 de 6 ','')
    text_aux = text_aux.replace('Pág. 3 de 6 ','')
    text_aux = text_aux.replace('Pág. 4 de 6 ','')
    text_aux = text_aux.replace('Pág. 5 de 6 ','')
    text_aux = text_aux.replace('Pág. 6 de 6 ','')
    text_aux = text_aux.replace('http://sjf2.scjn.gob.mx/detalle/tesis/','')
    text_aux = text_aux.replace(tesis_borrar,'')
    text_aux = text_aux.replace('  Fecha de impresión','')
    text_aux = text_aux.replace('Fecha de impresión','')
    text_aux = text_aux.replace(' 06/07/2021','')
    text_aux = text_aux.replace(' 07/07/2021','')
    text_aux = text_aux.replace(' 08/07/2021','')
    text_aux = text_aux.replace(' 09/07/2021','')
    text_aux = text_aux.replace(' 10/07/2021','')
    text_aux = text_aux.replace('  \x0c','')
    text_aux = text_aux.replace('######\x0c','')
    text_aux = text_aux.replace('Semanario Judicial de la Federación ','')
    text_aux = re.sub(r'Se formó jurisprudencia aunque no.*',"",text_aux)
    text_aux = text_aux.replace(r'(DA. 903/88. Impulsora Industrial de Ingeniería, S. A. de C. V. 15 de junio de 1988. Unanimidad de votos. Ponente: Genaro David Góngora Pimentel. Secretaria: Adriana Leticia Campuzano Gallegos)','')
    
    return text_aux